server:
  port: 8083

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:h2:mem:orders-db
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
