server:
  port: 8087

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:users-db
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

